/// visualizers/mod.rs
///
/// This file is intentionally minimal.  All `mod foo;` declarations and the
/// `all_visualizers()` factory are generated by build.rs into
/// $OUT_DIR/registry.rs and included here at compile time.
///
/// The generated file looks like:
///
///   mod fire;
///   mod lissajous;
///   mod matrix;
///   mod radial;
///   mod scope;
///   mod spectrum;
///
///   pub fn all_visualizers() -> Vec<Box<dyn Visualizer>> {
///       let mut out = Vec::new();
///       out.extend(fire::register());
///       out.extend(lissajous::register());
///       // ... etc
///       out
///   }
///
/// To add a new visualizer:
///   1. Create src/visualizers/mything.rs
///   2. Implement the Visualizer trait
///   3. Export:  pub fn register() -> Vec<Box<dyn Visualizer>> { ... }
///   4. Run:     cargo build
///
/// The new visualizer will appear automatically in --list and be selectable
/// by name on the CLI.  No other files need to be touched.

use crate::visualizer::Visualizer;

include!(concat!(env!("OUT_DIR"), "/registry.rs"));
