/// visualizers/mod.rs
///
/// This file is intentionally minimal.  All `mod foo;` declarations,
/// the `all_visualizers()` factory, and the `visualizer_categories()`
/// grouping function are generated by build.rs into $OUT_DIR/registry.rs
/// and included here at compile time.
///
/// Visualizers live in category subdirectories:
///
///   src/visualizers/
///     scopes/     — waveform / oscilloscope visualizers
///     frequency/  — frequency-domain / level visualizers
///     effects/    — generative artistic effects
///     abstract/   — abstract motion visualizers
///
/// The generated file looks roughly like:
///
///   #[path = "/abs/path/frequency/spectrum.rs"]
///   pub mod spectrum;
///   // ...
///
///   pub fn all_visualizers() -> Vec<Box<dyn Visualizer>> { ... }
///
///   pub fn visualizer_categories() -> Vec<(&'static str, Vec<&'static str>)> {
///       vec![
///           ("abstract",  vec!["orbit", "pulsar"]),
///           ("effects",   vec!["fire", "matrix", "plasma"]),
///           ("frequency", vec!["radial", "spectrum", "vu"]),
///           ("scopes",    vec!["lissajous", "scope"]),
///       ]
///   }
///
/// To add a new visualizer:
///   1. Create src/visualizers/<category>/mything.rs
///   2. Implement the Visualizer trait
///   3. Export:  pub fn register() -> Vec<Box<dyn Visualizer>> { ... }
///   4. Run:     cargo build
///
/// The new visualizer appears automatically in --list, the in-app picker,
/// and is selectable by its basename on the CLI.  No other files need
/// to be touched.

use crate::visualizer::Visualizer;

include!(concat!(env!("OUT_DIR"), "/registry.rs"));
