/// visualizers/mod.rs
///
/// This file is intentionally minimal.  All `mod foo;` declarations,
/// the `all_visualizers()` factory, and the `visualizer_categories()`
/// grouping function are generated by build.rs into $OUT_DIR/registry.rs
/// and included here at compile time.
///
/// Visualizers live in category subdirectories:
///
///   src/visualizers/
///     scopes/     — waveform / oscilloscope visualizers
///     frequency/  — frequency-domain / level visualizers
///
/// (Add more categories by creating new subdirectories — build.rs picks
/// them up automatically.)
///
/// To add a new visualizer:
///   1. Create src/visualizers/<category>/mything.rs
///      (plus mything.wgsl beside it if shader-based)
///   2. Implement the Visualizer trait
///   3. Export:  pub fn register() -> Vec<Box<dyn Visualizer>> { ... }
///   4. Run:     cargo build
///
/// The new visualizer appears automatically in --list and is selectable
/// by its basename on the CLI.  No other files need to be touched.

use crate::visualizer::Visualizer;

include!(concat!(env!("OUT_DIR"), "/registry.rs"));
